# Generated by Django 2.2.7 on 2019-11-23 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examtool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_id',
            field=models.IntegerField(default=0, verbose_name='カテゴリID'),
        ),
        migrations.AddField(
            model_name='category',
            name='sub_category_id',
            field=models.IntegerField(default=0, verbose_name='サブカテゴリID'),
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_no', models.IntegerField(default=0, verbose_name='選択肢番号')),
                ('answer', models.CharField(max_length=256, verbose_name='選択肢')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_category', to='examtool.Category', verbose_name='カテゴリ')),
            ],
        ),
    ]
