# Generated by Django 2.2.7 on 2019-11-23 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examtool', '0004_auto_20191123_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='id',
        ),
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='カテゴリID'),
        ),
    ]
